#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

OUT_DIR="generated/optimization"
REPORT_DIR="generated/reports"
REPORT="$REPORT_DIR/optimization_sweep.md"

mkdir -p "$OUT_DIR" "$REPORT_DIR"
rm -f "$OUT_DIR"/*.sv

count_matches() {
  local pattern="$1"
  local file="$2"
  grep -cE "$pattern" "$file" 2>/dev/null; true
}

count_fixed() {
  local pattern="$1"
  local file="$2"
  grep -cF "$pattern" "$file" 2>/dev/null; true
}

count_weighted_muls() {
  local file="$1"
  python3 - "$file" <<'PYEOF'
import sys, re, collections

with open(sys.argv[1]) as f:
    lines = f.readlines()

sections = {}
current = None
body = []
for line in lines:
    m = re.match(r'^module\s+(\w+)', line)
    if m:
        current = m.group(1)
        body = []
    elif line.strip() == 'endmodule' and current:
        sections[current] = body[:]
        current = None
        body = []
    elif current is not None:
        body.append(line)

own_muls = {mod: sum(1 for l in ls if ' * ' in l) for mod, ls in sections.items()}

inst_re = re.compile(r'^\s+(\w+)\s+\w+\s*\(')
children = {mod: collections.Counter() for mod in sections}
for mod, ls in sections.items():
    for line in ls:
        hit = inst_re.match(line)
        if hit:
            child = hit.group(1)
            if child in sections and child != mod:
                children[mod][child] += 1

all_children = {c for ch in children.values() for c in ch}
roots = [m for m in sections if m not in all_children]
if not roots:
    roots = list(sections.keys())

memo = {}
def weighted(mod):
    if mod in memo:
        return memo[mod]
    total = own_muls.get(mod, 0)
    for child, cnt in children[mod].items():
        total += cnt * weighted(child)
    memo[mod] = total
    return total

root = sorted(roots)[0]
print(weighted(root))
PYEOF
}

estimate_token_cycles() {
  local layers="$1"
  local mac_lanes="$2"
  local projection_cycles=$((4 * (4 / mac_lanes)))
  local mamba_layers=$((layers - 1))
  local attention_layers=1

  # Analytical estimate, not simulation-measured throughput.
  # Calibrated from the current latency-budget FSM decomposition:
  # Mamba layer:     mixer(3 slots) + conv + scan + MLP(3 slots)
  # Attention layer: QKV + attention-out + MLP(3 slots)
  local mamba_cycles=$((47 + 6 * projection_cycles))
  local attention_cycles=$((23 + 7 * projection_cycles))
  echo $((mamba_layers * mamba_cycles + attention_layers * attention_cycles))
}

echo "=== Generating optimization sweep SystemVerilog ==="
sbt "runMain jamba.top.GenerateScaleSweep $OUT_DIR"

echo "=== Writing optimization report ==="
{
  echo "# M8-O Projection MAC Parallelism Sweep"
  echo ""
  echo "Generated by \`scripts/optimization_sweep.sh\`."
  echo ""
  echo "Latency values are analytical estimates derived from FSM structure, not post-synthesis or simulation-measured throughput."
  echo ""
  echo "| Design | numLayers | contextLength | projectionMacLanes | Mul-proxy (file) | Mul-proxy (instance-weighted) | Add-proxy | Reg declarations | Estimated projection cycles | Estimated token cycles |"
  echo "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"

  for sv in "$OUT_DIR"/SinglePhysicalTile_*_Mac*.sv; do
    [ -f "$sv" ] || continue
    design="$(basename "$sv" .sv)"
    if [[ "$design" =~ SinglePhysicalTile_([0-9]+)L_Context([0-9]+)_Mac([0-9]+) ]]; then
      layers="${BASH_REMATCH[1]}"
      context="${BASH_REMATCH[2]}"
      mac_lanes="${BASH_REMATCH[3]}"
    else
      continue
    fi

    projection_cycles=$((4 * (4 / mac_lanes)))
    token_cycles="$(estimate_token_cycles "$layers" "$mac_lanes")"
    multiplies="$(count_fixed ' * ' "$sv")"
    weighted_muls="$(count_weighted_muls "$sv")"
    adds="$(count_fixed ' + ' "$sv")"
    regs="$(count_matches '^  reg ' "$sv")"

    echo "| $design | $layers | $context | $mac_lanes | $multiplies | $weighted_muls | $adds | $regs | $projection_cycles | $token_cycles |"
  done

  echo ""
  echo "## Interpretation"
  echo ""
  echo "- \`Mac1\` is the maximum-reuse baseline: one projection MAC lane, highest projection latency."
  echo "- \`Mac2\` is the balanced point: projection latency is halved while keeping the same unified scheduler."
  echo "- \`Mac4\` is the fastest projection setting: one row per cycle, at higher structural MAC cost."
  echo "- The estimate assumes one attention layer in each listed tile configuration, matching the emitted debug/formal configs."
} > "$REPORT"

cat "$REPORT"
echo ""
echo "Optimization sweep report written to $REPORT"
