#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

OUT_DIR="generated/resource_reuse"
REPORT_DIR="generated/reports"
REPORT="$REPORT_DIR/resource_reuse_comparison.md"

mkdir -p "$OUT_DIR" "$REPORT_DIR"
rm -f "$OUT_DIR"/*.sv

count_lines() {
  local pattern="$1"
  local file="$2"
  grep -cE "$pattern" "$file" 2>/dev/null; true
}

count_fixed_lines() {
  local pattern="$1"
  local file="$2"
  grep -cF "$pattern" "$file" 2>/dev/null; true
}

echo "=== Generating resource-reuse SystemVerilog ==="
sbt "runMain jamba.top.GenerateResourceReuseSweep $OUT_DIR"

echo "=== Writing resource-reuse report ==="
{
  echo "# Resource Reuse Comparison Report"
  echo ""
  echo "Generated by \`scripts/resource_reuse_analysis.sh\`."
  echo ""
  echo "This is a generated-Verilog structure report for the first resource-reuse fabric. It is not a post-synthesis LUT/FF/BRAM/DSP report."
  echo ""
  echo "| Design | Bytes | Lines | Modules | assign | Reg declarations | Multiply-line proxy | Add-line proxy |"
  echo "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"

  for sv in "$OUT_DIR"/*.sv; do
    design="$(basename "$sv" .sv)"
    bytes="$(wc -c < "$sv" | tr -d ' ')"
    lines="$(wc -l < "$sv" | tr -d ' ')"
    modules="$(count_lines '^module ' "$sv")"
    assigns="$(count_lines '^  assign ' "$sv")"
    regs="$(count_lines '^  reg ' "$sv")"
    multiplies="$(count_fixed_lines ' * ' "$sv")"
    adds="$(count_fixed_lines ' + ' "$sv")"
    echo "| $design | $bytes | $lines | $modules | $assigns | $regs | $multiplies | $adds |"
  done

  echo ""
  echo "## Reading The Report"
  echo ""
  echo "- \`*_Baseline\` designs are the original direct operator implementations."
  echo "- \`*_SharedFabric\` designs instantiate the reusable fabric modules."
  echo "- Multiply and add counts are line-based proxies from generated SystemVerilog, not synthesis resource counts."
  echo "- Shared-fabric versions may be larger before time multiplexing because module boundaries are explicit."
  echo ""
  echo "## Generated Files"
  echo ""
  for sv in "$OUT_DIR"/*.sv; do
    echo "- \`$sv\`"
  done
} > "$REPORT"

cat "$REPORT"
echo ""
echo "Resource reuse report written to $REPORT"
