#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

OUT_DIR="generated/resource_reuse"
REPORT_DIR="generated/reports"
REPORT="$REPORT_DIR/resource_reuse_comparison.md"

mkdir -p "$OUT_DIR" "$REPORT_DIR"
rm -f "$OUT_DIR"/*.sv

count_lines() {
  local pattern="$1"
  local file="$2"
  grep -cE "$pattern" "$file" 2>/dev/null; true
}

count_fixed_lines() {
  local pattern="$1"
  local file="$2"
  grep -cF "$pattern" "$file" 2>/dev/null; true
}

count_reg_bits() {
  local file="$1"
  (grep -oE 'reg[[:space:]]+\[[0-9]+:0\]' "$file" 2>/dev/null || true) \
    | sed -E 's/.*\[([0-9]+):0\]/\1/' \
    | awk '{sum += $1+1} END {print sum+0}'
}

echo "=== Generating resource-reuse SystemVerilog ==="
sbt "runMain jamba.top.GenerateResourceReuseSweep $OUT_DIR"

echo "=== Writing resource-reuse report ==="
{
  echo "# Resource Reuse Comparison Report"
  echo ""
  echo "Generated by \`scripts/resource_reuse_analysis.sh\`."
  echo ""
  echo "This is a generated-Verilog structure report for the first resource-reuse fabric. It is not a post-synthesis LUT/FF/BRAM/DSP report."
  echo ""
  echo "| Design | Bytes | Lines | Modules | assign | Reg declarations | Multiply-line proxy | Add-line proxy |"
  echo "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"

  for sv in "$OUT_DIR"/*.sv; do
    design="$(basename "$sv" .sv)"
    bytes="$(wc -c < "$sv" | tr -d ' ')"
    lines="$(wc -l < "$sv" | tr -d ' ')"
    modules="$(count_lines '^module ' "$sv")"
    assigns="$(count_lines '^  assign ' "$sv")"
    regs="$(count_lines '^  reg ' "$sv")"
    multiplies="$(count_fixed_lines ' * ' "$sv")"
    adds="$(count_fixed_lines ' + ' "$sv")"
    echo "| $design | $bytes | $lines | $modules | $assigns | $regs | $multiplies | $adds |"
  done

  echo ""
  echo "## Quantization Precision Sweep (UnifiedJamba2MiniLayer, debug config)"
  echo ""
  echo "Multiply-line proxy is structural (same MAC count across precisions)."
  echo "Total reg bits is a proxy for accumulator/state storage width reduction."
  echo ""
  echo "| Design | Mul-line proxy | Add-line proxy | Total reg bits |"
  echo "| --- | ---: | ---: | ---: |"

  for sv in "$OUT_DIR"/Jamba2MiniLayer_UnifiedSerial_INT*.sv; do
    [ -f "$sv" ] || continue
    design="$(basename "$sv" .sv)"
    multiplies="$(count_fixed_lines ' * ' "$sv")"
    adds="$(count_fixed_lines ' + ' "$sv")"
    reg_bits="$(count_reg_bits "$sv")"
    echo "| $design | $multiplies | $adds | $reg_bits |"
  done

  echo ""
  echo "## Tile-Level Modules"
  echo ""
  echo "Full tile hierarchy: TileScheduler orchestrates the layer, FullTile adds weight store, AcceleratorTile is the top-level."
  echo ""
  echo "| Design | Bytes | Lines | Modules | Reg declarations | Mul-line proxy |"
  echo "| --- | ---: | ---: | ---: | ---: | ---: |"

  for sv in \
      "$OUT_DIR/TileScheduler_UnifiedSerial.sv" \
      "$OUT_DIR/FullTile_UnifiedSerial.sv" \
      "$OUT_DIR/AcceleratorTile_UnifiedSerial.sv" \
      "$OUT_DIR/WeightStore_Layered.sv"; do
    [ -f "$sv" ] || continue
    design="$(basename "$sv" .sv)"
    bytes="$(wc -c < "$sv" | tr -d ' ')"
    lines="$(wc -l < "$sv" | tr -d ' ')"
    modules="$(count_lines '^module ' "$sv")"
    regs="$(count_lines '^  reg ' "$sv")"
    multiplies="$(count_fixed_lines ' * ' "$sv")"
    echo "| $design | $bytes | $lines | $modules | $regs | $multiplies |"
  done

  echo ""
  echo "## Sparsification: Zero-Skip MAC Variants"
  echo ""
  echo "ZeroSkip adds a comparator gate: if a==0 or b==0, the multiply is bypassed (accIn passed through)."
  echo "Multiply-line proxy stays the same (structural); extra assign lines from comparator/Mux appear."
  echo ""
  echo "| Design | Mul-line proxy | Add-line proxy | Reg declarations |"
  echo "| --- | ---: | ---: | ---: |"

  for sv in \
      "$OUT_DIR/MacLane_ResourceReuse.sv" \
      "$OUT_DIR/MacLane_ZeroSkip.sv" \
      "$OUT_DIR/MacLaneMixed_ZeroSkip.sv" \
      "$OUT_DIR/Linear4_SerialSharedFabric.sv" \
      "$OUT_DIR/Linear4_SerialSharedFabric_ZeroSkip.sv" \
      "$OUT_DIR/SelectiveScanMini_SerialSharedFabric_ZeroSkip.sv" \
      "$OUT_DIR/Jamba2MiniLayer_UnifiedSerial_ZeroSkip.sv"; do
    [ -f "$sv" ] || continue
    design="$(basename "$sv" .sv)"
    multiplies="$(count_fixed_lines ' * ' "$sv")"
    adds="$(count_fixed_lines ' + ' "$sv")"
    regs="$(count_lines '^  reg ' "$sv")"
    echo "| $design | $multiplies | $adds | $regs |"
  done

  echo ""
  echo "## Reading The Report"
  echo ""
  echo "- \`*_Baseline\` designs are the original direct operator implementations."
  echo "- \`*_SharedFabric\` designs instantiate the reusable fabric modules."
  echo "- Multiply and add counts are line-based proxies from generated SystemVerilog, not synthesis resource counts."
  echo "- Shared-fabric versions may be larger before time multiplexing because module boundaries are explicit."
  echo ""
  echo "## Generated Files"
  echo ""
  for sv in "$OUT_DIR"/*.sv; do
    echo "- \`$sv\`"
  done
} > "$REPORT"

cat "$REPORT"
echo ""
echo "Resource reuse report written to $REPORT"
