#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

OUT_DIR="generated/resource_reuse"
REPORT_DIR="generated/reports"
REPORT="$REPORT_DIR/resource_reuse_comparison.md"

mkdir -p "$OUT_DIR" "$REPORT_DIR"
rm -f "$OUT_DIR"/*.sv

count_lines() {
  local pattern="$1"
  local file="$2"
  grep -cE "$pattern" "$file" 2>/dev/null; true
}

count_fixed_lines() {
  local pattern="$1"
  local file="$2"
  grep -cF "$pattern" "$file" 2>/dev/null; true
}

count_reg_bits() {
  local file="$1"
  (grep -oE 'reg[[:space:]]+\[[0-9]+:0\]' "$file" 2>/dev/null || true) \
    | sed -E 's/.*\[([0-9]+):0\]/\1/' \
    | awk '{sum += $1+1} END {print sum+0}'
}

# Instance-weighted multiply-line proxy.
# Parses the SV file into per-module sections, builds an instantiation graph,
# and recursively sums (own_muls + sum(child_count * weighted(child))).
# This correctly counts a module that is instantiated N times as N × its cost,
# unlike grep which counts each module definition once regardless of instance count.
count_weighted_muls() {
  local file="$1"
  python3 - "$file" <<'PYEOF'
import sys, re, collections

with open(sys.argv[1]) as f:
    lines = f.readlines()

sections = {}
current = None
body = []
for line in lines:
    m = re.match(r'^module\s+(\w+)', line)
    if m:
        current = m.group(1)
        body = []
    elif line.strip() == 'endmodule' and current:
        sections[current] = body[:]
        current = None
        body = []
    elif current is not None:
        body.append(line)

own_muls = {mod: sum(1 for l in ls if ' * ' in l) for mod, ls in sections.items()}

inst_re = re.compile(r'^\s+(\w+)\s+\w+\s*\(')
children = {mod: collections.Counter() for mod in sections}
for mod, ls in sections.items():
    for line in ls:
        hit = inst_re.match(line)
        if hit:
            child = hit.group(1)
            if child in sections and child != mod:
                children[mod][child] += 1

all_children = {c for ch in children.values() for c in ch}
roots = [m for m in sections if m not in all_children]
if not roots:
    roots = list(sections.keys())

memo = {}
def weighted(mod):
    if mod in memo:
        return memo[mod]
    total = own_muls.get(mod, 0)
    for child, cnt in children[mod].items():
        total += cnt * weighted(child)
    memo[mod] = total
    return total

root = sorted(roots)[0]
print(weighted(root))
PYEOF
}

echo "=== Generating resource-reuse SystemVerilog ==="
sbt "runMain jamba.top.GenerateResourceReuseSweep $OUT_DIR"

echo "=== Writing resource-reuse report ==="
{
  echo "# Resource Reuse Comparison Report"
  echo ""
  echo "Generated by \`scripts/resource_reuse_analysis.sh\`."
  echo ""
  echo "This is a generated-Verilog structure report for the first resource-reuse fabric. It is not a post-synthesis LUT/FF/BRAM/DSP report."
  echo ""
  echo "**Multiply-line proxy**: lines containing \` * \` across all module *definitions* in the file."
  echo "**Instance-weighted proxy**: same count but each module is multiplied by how many times it is instantiated."
  echo "For flat designs with no sub-module reuse the two metrics are equal. For hierarchical designs"
  echo "(e.g. multi-layer tiles or shared-fabric modules) the instance-weighted number correctly"
  echo "reflects that a sub-module instantiated N times contributes N × its own mul count."
  echo ""
  echo "| Design | Bytes | Lines | Modules | assign | Reg decls | Mul-proxy (file) | Mul-proxy (instance-weighted) | Add-proxy |"
  echo "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"

  for sv in "$OUT_DIR"/*.sv; do
    design="$(basename "$sv" .sv)"
    bytes="$(wc -c < "$sv" | tr -d ' ')"
    lines="$(wc -l < "$sv" | tr -d ' ')"
    modules="$(count_lines '^module ' "$sv")"
    assigns="$(count_lines '^  assign ' "$sv")"
    regs="$(count_lines '^  reg ' "$sv")"
    multiplies="$(count_fixed_lines ' * ' "$sv")"
    weighted_muls="$(count_weighted_muls "$sv")"
    adds="$(count_fixed_lines ' + ' "$sv")"
    echo "| $design | $bytes | $lines | $modules | $assigns | $regs | $multiplies | $weighted_muls | $adds |"
  done

  echo ""
  echo "## Quantization Precision Sweep (UnifiedJamba2MiniLayer, debug config)"
  echo ""
  echo "Multiply-line proxy is structural (same MAC count across precisions)."
  echo "Total reg bits is a proxy for accumulator/state storage width reduction."
  echo ""
  echo "| Design | Mul-line proxy | Add-line proxy | Total reg bits |"
  echo "| --- | ---: | ---: | ---: |"

  for sv in "$OUT_DIR"/Jamba2MiniLayer_UnifiedSerial_INT*.sv; do
    [ -f "$sv" ] || continue
    design="$(basename "$sv" .sv)"
    multiplies="$(count_fixed_lines ' * ' "$sv")"
    adds="$(count_fixed_lines ' + ' "$sv")"
    reg_bits="$(count_reg_bits "$sv")"
    echo "| $design | $multiplies | $adds | $reg_bits |"
  done

  echo ""
  echo "## Tile-Level Modules"
  echo ""
  echo "Full tile hierarchy: TileScheduler orchestrates the layer, FullTile adds weight store, AcceleratorTile is the top-level."
  echo ""
  echo "| Design | Bytes | Lines | Modules | Reg declarations | Mul-line proxy |"
  echo "| --- | ---: | ---: | ---: | ---: | ---: |"

  for sv in \
      "$OUT_DIR/TileScheduler_UnifiedSerial.sv" \
      "$OUT_DIR/FullTile_UnifiedSerial.sv" \
      "$OUT_DIR/AcceleratorTile_UnifiedSerial.sv" \
      "$OUT_DIR/WeightStore_Layered.sv"; do
    [ -f "$sv" ] || continue
    design="$(basename "$sv" .sv)"
    bytes="$(wc -c < "$sv" | tr -d ' ')"
    lines="$(wc -l < "$sv" | tr -d ' ')"
    modules="$(count_lines '^module ' "$sv")"
    regs="$(count_lines '^  reg ' "$sv")"
    multiplies="$(count_fixed_lines ' * ' "$sv")"
    echo "| $design | $bytes | $lines | $modules | $regs | $multiplies |"
  done

  echo ""
  echo "## Sparsification: Zero-Skip MAC Variants"
  echo ""
  echo "ZeroSkip adds a comparator gate: if a==0 or b==0, the multiply is bypassed (accIn passed through)."
  echo "Multiply-line proxy stays the same (structural); extra assign lines from comparator/Mux appear."
  echo ""
  echo "| Design | Mul-line proxy | Add-line proxy | Reg declarations |"
  echo "| --- | ---: | ---: | ---: |"

  for sv in \
      "$OUT_DIR/MacLane_ResourceReuse.sv" \
      "$OUT_DIR/MacLane_ZeroSkip.sv" \
      "$OUT_DIR/MacLaneMixed_ZeroSkip.sv" \
      "$OUT_DIR/Linear4_SerialSharedFabric.sv" \
      "$OUT_DIR/Linear4_SerialSharedFabric_ZeroSkip.sv" \
      "$OUT_DIR/SelectiveScanMini_SerialSharedFabric_ZeroSkip.sv" \
      "$OUT_DIR/Jamba2MiniLayer_UnifiedSerial_ZeroSkip.sv"; do
    [ -f "$sv" ] || continue
    design="$(basename "$sv" .sv)"
    multiplies="$(count_fixed_lines ' * ' "$sv")"
    adds="$(count_fixed_lines ' + ' "$sv")"
    regs="$(count_lines '^  reg ' "$sv")"
    echo "| $design | $multiplies | $adds | $regs |"
  done

  echo ""
  echo "## Reading The Report"
  echo ""
  echo "- \`*_Baseline\` designs are the original direct operator implementations."
  echo "- \`*_SharedFabric\` designs instantiate the reusable fabric modules."
  echo "- Multiply and add counts are line-based proxies from generated SystemVerilog, not synthesis resource counts."
  echo "- Shared-fabric versions may be larger before time multiplexing because module boundaries are explicit."
  echo ""
  echo "## Generated Files"
  echo ""
  for sv in "$OUT_DIR"/*.sv; do
    echo "- \`$sv\`"
  done
} > "$REPORT"

cat "$REPORT"
echo ""
echo "Resource reuse report written to $REPORT"
