#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

OUT_DIR="generated/scale"
REPORT_DIR="generated/reports"
REPORT="$REPORT_DIR/scale_analysis.md"

mkdir -p "$OUT_DIR" "$REPORT_DIR"
rm -f "$OUT_DIR"/*.sv

count_matches() {
  local pattern="$1"
  local file="$2"
  grep -cE "$pattern" "$file" 2>/dev/null; true
}

count_fixed() {
  local pattern="$1"
  local file="$2"
  grep -cF "$pattern" "$file" 2>/dev/null; true
}

echo "=== Generating scale sweep SystemVerilog ==="
sbt "runMain jamba.top.GenerateScaleSweep $OUT_DIR"

echo "=== Writing scale report ==="
{
  echo "# Scale Analysis Report"
  echo ""
  echo "Generated by \`scripts/scale_analysis.sh\`."
  echo ""
  echo "This is a lightweight elaboration and generated-Verilog size report. It is not a post-synthesis LUT/FF/BRAM/DSP report."
  echo ""
  echo "| Design | Bytes | Lines | Modules | Reg declarations | Multiply-line proxy | Add-line proxy |"
  echo "| --- | ---: | ---: | ---: | ---: | ---: | ---: |"

  for sv in "$OUT_DIR"/*.sv; do
    design="$(basename "$sv" .sv)"
    bytes="$(wc -c < "$sv" | tr -d ' ')"
    lines="$(wc -l < "$sv" | tr -d ' ')"
    modules="$(count_matches '^module ' "$sv")"
    regs="$(count_matches '^  reg ' "$sv")"
    multiplies="$(count_fixed ' * ' "$sv")"
    adds="$(count_fixed ' + ' "$sv")"
    echo "| $design | $bytes | $lines | $modules | $regs | $multiplies | $adds |"
  done

  echo ""
  echo "## Generated Files"
  echo ""
  for sv in "$OUT_DIR"/*.sv; do
    echo "- \`$sv\`"
  done
} > "$REPORT"

cat "$REPORT"
echo ""
echo "Scale analysis report written to $REPORT"
