#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

OUT_DIR="generated/scale"
REPORT_DIR="generated/reports"
REPORT="$REPORT_DIR/scale_analysis.md"

mkdir -p "$OUT_DIR" "$REPORT_DIR"
rm -f "$OUT_DIR"/*.sv

count_matches() {
  local pattern="$1"
  local file="$2"
  local count
  count="$(rg -c "$pattern" "$file" || true)"
  if [ -z "$count" ]; then
    echo "0"
  else
    echo "$count"
  fi
}

echo "=== Generating scale sweep SystemVerilog ==="
sbt "runMain jamba.top.GenerateScaleSweep $OUT_DIR"

echo "=== Writing scale report ==="
{
  echo "# Scale Analysis Report"
  echo ""
  echo "Generated by \`scripts/scale_analysis.sh\`."
  echo ""
  echo "This is a lightweight elaboration and generated-Verilog size report. It is not a post-synthesis LUT/FF/BRAM/DSP report."
  echo ""
  echo "| Design | Bytes | Lines | Modules | always_ff | assign | Reg declarations |"
  echo "| --- | ---: | ---: | ---: | ---: | ---: | ---: |"

  for sv in "$OUT_DIR"/*.sv; do
    design="$(basename "$sv" .sv)"
    bytes="$(wc -c < "$sv" | tr -d ' ')"
    lines="$(wc -l < "$sv" | tr -d ' ')"
    modules="$(count_matches '^module ' "$sv")"
    always_ff="$(count_matches 'always_ff' "$sv")"
    assigns="$(count_matches '^  assign ' "$sv")"
    regs="$(count_matches '^  reg ' "$sv")"
    echo "| $design | $bytes | $lines | $modules | $always_ff | $assigns | $regs |"
  done

  echo ""
  echo "## Generated Files"
  echo ""
  for sv in "$OUT_DIR"/*.sv; do
    echo "- \`$sv\`"
  done
} > "$REPORT"

cat "$REPORT"
echo ""
echo "Scale analysis report written to $REPORT"
