#!/usr/bin/env bash
# Sparsification analysis: compare zero-skip vs dense MAC variants.
#
# Zero-skip bypasses the multiply when either operand is zero.
# At 50% input sparsity (half of x/state elements are zero), roughly half
# of all multiply cycles are skipped in time-multiplexed designs.
#
# Run after resource_reuse_analysis.sh has already generated the .sv files,
# or set REGENERATE=1 to force a fresh sbt generation.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT_DIR="generated/resource_reuse"
REPORT_DIR="generated/reports"
REPORT="$REPORT_DIR/sparsification_comparison.md"

mkdir -p "$OUT_DIR" "$REPORT_DIR"

if [[ "${REGENERATE:-0}" == "1" ]]; then
  echo "=== Regenerating SystemVerilog (REGENERATE=1) ==="
  sbt "runMain jamba.top.GenerateResourceReuseSweep $OUT_DIR"
fi

count_fixed_lines() {
  local pattern="$1"
  local file="$2"
  grep -cF "$pattern" "$file" 2>/dev/null; true
}

count_lines() {
  local pattern="$1"
  local file="$2"
  grep -cE "$pattern" "$file" 2>/dev/null; true
}

# Print a row: design, mul proxy, add proxy, regs, structural skip estimate at 50% sparsity.
# Note: mul-line proxy counts physical multiplier lines in the generated SV, not dynamic
# MAC-cycle count. For time-multiplexed designs one multiplier line covers many cycles.
# The skip-estimate column is (mul_proxy / 2) — a structural upper bound, not a measured
# cycle count. Actual dynamic savings depend on runtime activation/weight sparsity.
print_row() {
  local sv="$1"
  [ -f "$sv" ] || return
  local design; design="$(basename "$sv" .sv)"
  local muls; muls="$(count_fixed_lines ' * ' "$sv")"
  local adds; adds="$(count_fixed_lines ' + ' "$sv")"
  local regs; regs="$(count_lines '^  reg ' "$sv")"
  local skip_est=$(( (muls + 1) / 2 ))
  echo "| $design | $muls | $adds | $regs | ~$skip_est |"
}

{
  echo "# Sparsification (Zero-Skip) Analysis"
  echo ""
  echo "Generated by \`scripts/sparsification_analysis.sh\`."
  echo ""
  echo "## What Is Zero-Skip?"
  echo ""
  echo "When \`zeroSkip=true\`, a comparator gates the multiplier:"
  echo "\`\`\`"
  echo "if a == 0 || b == 0: accOut = accIn   // bypass: no multiply"
  echo "else:                 accOut = a*b + accIn"
  echo "\`\`\`"
  echo "At 50% input sparsity (ReLU activations or pruned weights), roughly half of"
  echo "all multiply-accumulate cycles are eliminated in time-multiplexed designs."
  echo ""
  echo "## MacLane Variants"
  echo ""
  echo "| Design | Mul-line proxy | Add-line proxy | Reg declarations | Skip est. @ 50% sparsity (structural) |"
  echo "| --- | ---: | ---: | ---: | ---: |"
  print_row "$OUT_DIR/MacLane_ResourceReuse.sv"
  print_row "$OUT_DIR/MacLane_ZeroSkip.sv"
  print_row "$OUT_DIR/MacLaneMixed_ZeroSkip.sv"

  echo ""
  echo "## Linear Layer Variants"
  echo ""
  echo "| Design | Mul-line proxy | Add-line proxy | Reg declarations | Skip est. @ 50% sparsity (structural) |"
  echo "| --- | ---: | ---: | ---: | ---: |"
  print_row "$OUT_DIR/Linear4_SerialSharedFabric.sv"
  print_row "$OUT_DIR/Linear4_SerialSharedFabric_ZeroSkip.sv"

  echo ""
  echo "## Selective Scan Variants"
  echo ""
  echo "| Design | Mul-line proxy | Add-line proxy | Reg declarations | Skip est. @ 50% sparsity (structural) |"
  echo "| --- | ---: | ---: | ---: | ---: |"
  print_row "$OUT_DIR/SelectiveScanMini_SerialSharedFabric.sv"
  print_row "$OUT_DIR/SelectiveScanMini_SerialSharedFabric_ZeroSkip.sv"

  echo ""
  echo "## Full Layer Variants"
  echo ""
  echo "| Design | Mul-line proxy | Add-line proxy | Reg declarations | Skip est. @ 50% sparsity (structural) |"
  echo "| --- | ---: | ---: | ---: | ---: |"
  print_row "$OUT_DIR/Jamba2MiniLayer_UnifiedSerial.sv"
  print_row "$OUT_DIR/Jamba2MiniLayer_UnifiedSerial_ZeroSkip.sv"

  echo ""
  echo "## Notes"
  echo ""
  echo "- Mul-line proxy counts lines containing \` * \` in the generated SystemVerilog."
  echo "  For time-multiplexed designs (SerialSharedFabric, UnifiedSerial) this equals"
  echo "  the number of physical multipliers, not the operation count."
  echo "- Skip estimate is ⌈mul_proxy / 2⌉ — a structural upper bound at 50% sparsity."
  echo "  Mul-line proxy counts physical multiplier lines in the generated SV; for"
  echo "  time-multiplexed designs one multiplier covers many MAC cycles, so this is"
  echo "  NOT a dynamic cycle-saved count. Actual savings depend on runtime sparsity."
  echo "- ZeroSkip adds a comparator (an OR gate on sign-extended inputs) and a Mux."
  echo "  The area overhead is one ~N-bit OR plus one ~N-bit Mux per MAC."
} > "$REPORT"

cat "$REPORT"
echo ""
echo "Sparsification report written to $REPORT"
